# EDA – Tổng quan dữ liệu và trả lời câu hỏi

In [54]:
import pandas as pd

PRE_MERGED = "../data/unified/preprocessed_merged.csv"

df = pd.read_csv(PRE_MERGED, encoding="utf-8-sig", encoding_errors="ignore", on_bad_lines="skip")

## 1) Tổng quan dữ liệu

In [55]:
df.columns

Index(['tieu_de', 'gia', 'dia_chi', 'dien_tich_dat', 'phong_ngu', 'phong_tam',
       'so_tang', 'phap_ly', 'ngay_dang', 'gia_tren_m2', 'diem_sinh_loi'],
      dtype='object')

### 1.1 Ý nghĩa của từng cột dữ liệu
- tieu_de: Tiêu đề bài đăng bán nhà
- gia: Giá bán (theo tỷ đồng)
- dia_chi: Địa chỉ nhà
- dien_tich_dat: Diện tích đất (theo mét vuông)
- phong_ngu: Số phòng ngủ của nhà
- phong_tam: Số phòng tắm của nhà
- so_tang: Số tầng của nhà
- phap_ly: Tình trạng pháp lý (Sổ hồng, Số đỏ, Giấy tờ không xác định)
- ngay_dang: Ngày đăng tin bán nhà
- gia_tren_m2: Giá đất trên mét vuông 
- diem_sinh_loi: Điểm số mà dòng tiền mang lại khi cho thuê

### 1.2 Kiểu dữ liệu của từng cột hiện tại

In [56]:
df.dtypes

tieu_de           object
gia              float64
dia_chi           object
dien_tich_dat    float64
phong_ngu        float64
phong_tam        float64
so_tang          float64
phap_ly           object
ngay_dang         object
gia_tren_m2      float64
diem_sinh_loi    float64
dtype: object

### 1.3 Kiểm tra và xử lí số dòng thiếu và trùng lặp

In [57]:
print("Số dòng:", len(df))
print("Số ô missing value:", df.isna().sum().sum())
print("Số dòng bị trùng lặp (tính cả dòng giống hệt nhau):", df.duplicated().sum())

Số dòng: 6974
Số ô missing value: 0
Số dòng bị trùng lặp (tính cả dòng giống hệt nhau): 5

In [58]:
df = df.drop_duplicates(inplace=False)
print("Số dòng sau khi xoá trùng lặp:", len(df))

Số dòng sau khi xoá trùng lặp: 6969

### 1.4 Phân tích dữ liệu với các dữ liệu kiểu object

In [59]:
print("Số giá trị duy nhất của tiêu đề là: ",df['tieu_de'].nunique())
print("Số giá trị duy nhất của địa chỉ là: ", df['dia_chi'].nunique())
print("Số giá trị duy nhất của pháp lý là: ", df['phap_ly'].nunique(),df['phap_ly'].unique())
print("Số giá trị duy nhất của ngày đăng là: ", df['ngay_dang'].nunique())

df['ngay_dang'] = pd.to_datetime(df['ngay_dang'], errors='coerce')
print("Ngày đăng lớn nhất",df['ngay_dang'].min().date())
print("Ngày đăng lớn nhất:", df['ngay_dang'].max().date())

df.columns

Số giá trị duy nhất của tiêu đề là:  6431
Số giá trị duy nhất của địa chỉ là:  3433
Số giá trị duy nhất của pháp lý là:  3 ['Sổ hồng' 'Sổ đỏ' 'Giấy tờ không xác định']
Số giá trị duy nhất của ngày đăng là:  250
Ngày đăng lớn nhất 2024-10-31
Ngày đăng lớn nhất: 2025-11-28

Index(['tieu_de', 'gia', 'dia_chi', 'dien_tich_dat', 'phong_ngu', 'phong_tam',
       'so_tang', 'phap_ly', 'ngay_dang', 'gia_tren_m2', 'diem_sinh_loi'],
      dtype='object')

### 1.4 Phân tích và xử lí dữ liệu với các dữ liệu dạng numeric

In [60]:
df.describe()

,gia,dien_tich_dat,phong_ngu,phong_tam,so_tang,ngay_dang,gia_tren_m2,diem_sinh_loi
count,6969.000000,6969.000000,6969.000000,6969.000000,6969.000000,6969,6969.000000,6969.000000
mean,25.774968,75.194897,4.800402,4.736978,6.015067,2025-10-12 01:24:18.286698240,0.450439,16.743609
min,0.014000,1.500000,1.000000,1.000000,1.000000,2024-10-31 00:00:00,0.000000,3.500000
25%,6.400000,38.400000,3.000000,3.000000,3.000000,2025-10-16 00:00:00,0.130000,11.000000
50%,9.300000,54.200000,4.000000,4.000000,4.000000,2025-11-18 00:00:00,0.200000,13.000000
75%,17.600000,80.000000,5.000000,5.000000,5.000000,2025-11-25 00:00:00,0.280000,17.800000
max,9400.000000,6117.000000,100.000000,101.000000,9810.000000,2025-11-28 00:00:00,228.330000,9828.000000
std,246.665084,125.004374,4.869499,4.843872,117.520627,NaN,6.183518,117.917222

In [ ]:
# Xử lí outlier dựa theo cảm quan và quan sát thủ công dữ liệu
cf = df[(df['gia'] <=500) & (df['so_tang'] <= 20) & (df['phong_ngu'] <= 30) & (df['phong_tam'] <= 30) & (df['dien_tich_dat'] <= 3000)]

cf.describe()

,gia,dien_tich_dat,phong_ngu,phong_tam,so_tang,ngay_dang,gia_tren_m2,diem_sinh_loi
count,6888.000000,6888.000000,6888.000000,6888.000000,6888.000000,6888,6888.000000,6888.000000
mean,16.657832,72.093357,4.516696,4.453833,4.460656,2025-10-12 02:10:02.090592512,0.224845,14.824731
min,0.014000,5.000000,1.000000,1.000000,1.000000,2024-10-31 00:00:00,0.000000,3.500000
25%,6.350000,38.000000,3.000000,3.000000,3.000000,2025-10-16 00:00:00,0.130000,11.000000
50%,9.200000,54.000000,4.000000,4.000000,4.000000,2025-11-17 12:00:00,0.200000,13.000000
75%,17.000000,80.000000,5.000000,5.000000,5.000000,2025-11-25 00:00:00,0.270000,17.000000
max,450.000000,2515.000000,30.000000,30.000000,20.000000,2025-11-28 00:00:00,9.000000,86.360000
std,25.687413,81.348576,2.993388,3.009045,2.145950,NaN,0.179041,7.097847